version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: ecoclean-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: ecoclean

  api:
    build: .
    container_name: ecoclean-api
    restart: unless-stopped
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/ecoclean
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads

volumes:
  mongodb_data:
